# BiomeAnnouncer Configuration

# Update Checker Settings
update-checker:
  # Set to false to disable update checking
  enabled: true

# Animation Settings
animation:
  # How fast the text appears (in ticks, lower = faster)
  # 2 = very fast, 3 = normal, 4 = slow
  typing-speed: 3

  # text color
  color: "&a"
  
  # Sound played while typing
  sound:
    # Set to false to disable the typing sound
    enabled: false
    # Volume of the sound (0.0 - 1.0)
    volume: 0.3
    # Pitch of the sound (0.5 - 2.0)
    pitch: 2.0

# Cooldown Settings
cooldown:
  # How long to wait before showing another biome announcement (in seconds)
  duration: 3 # seconds

# Messages
messages:
  prefix: "&8[&aBiome&8]&r"
  enabled: "&a Biome announcements enabled!"
  disabled: "&c Biome announcements disabled!"
  no-permission: "&cYou don't have permission to use this command!"

# Worlds where the plugin will work
enabled-worlds:
  - "world"
  - "world_nether"
  - "world_the_end"

# Join our discord server if you need any help - https://discord.gg/primalmc