name: BiomeAnnouncer
version: 1.1
main: org.example.BiomeAnnouncer
api-version: 1.13
commands:
  togglebiomeannouncer:
    description: Toggle biome announcements
    usage: /<command>
    permission: biomeannouncer.toggle
permissions:
  biomeannouncer.toggle:
    description: Allows toggling biome announcements
    default: true